require 'active_support/all'
require 'singleton'
require 'hashie'
require 'faraday'
require 'typhoeus/adapters/faraday'
require 'pararest/version'
require 'pararest/client'
require 'pararest/request/base'
require 'pararest/request/rakuten'
require 'pararest/request/yahoo_auctions'
require 'pararest/request/yahoo_shopping'

